name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Update npm
        run: npm install -g npm@10

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npx run lint

      - name: Run tests
        run: npm run test
